// Code generated by MockGen. DO NOT EDIT.
// Source: utils/file_store.go

// Package mock_utils is a generated GoMock package.
package sync

import (
	reflect "reflect"
	time "time"

	utils "github.com/chrismcgehee/lyncser/utils"
	gomock "github.com/golang/mock/gomock"
)

// MockFileStore is a mock of FileStore interface.
type MockFileStore struct {
	ctrl     *gomock.Controller
	recorder *MockFileStoreMockRecorder
}

// MockFileStoreMockRecorder is the mock recorder for MockFileStore.
type MockFileStoreMockRecorder struct {
	mock *MockFileStore
}

// NewMockFileStore creates a new mock instance.
func NewMockFileStore(ctrl *gomock.Controller) *MockFileStore {
	mock := &MockFileStore{ctrl: ctrl}
	mock.recorder = &MockFileStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStore) EXPECT() *MockFileStoreMockRecorder {
	return m.recorder
}

// CreateFile mocks base method.
func (m *MockFileStore) CreateFile(path utils.SyncedFile) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateFile", path)
}

// CreateFile indicates an expected call of CreateFile.
func (mr *MockFileStoreMockRecorder) CreateFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*MockFileStore)(nil).CreateFile), path)
}

// DownloadFile mocks base method.
func (m *MockFileStore) DownloadFile(path utils.SyncedFile) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DownloadFile", path)
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockFileStoreMockRecorder) DownloadFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockFileStore)(nil).DownloadFile), path)
}

// FileExists mocks base method.
func (m *MockFileStore) FileExists(path utils.SyncedFile) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// FileExists indicates an expected call of FileExists.
func (mr *MockFileStoreMockRecorder) FileExists(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockFileStore)(nil).FileExists), path)
}

// GetModifiedTime mocks base method.
func (m *MockFileStore) GetModifiedTime(path utils.SyncedFile) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModifiedTime", path)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetModifiedTime indicates an expected call of GetModifiedTime.
func (mr *MockFileStoreMockRecorder) GetModifiedTime(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModifiedTime", reflect.TypeOf((*MockFileStore)(nil).GetModifiedTime), path)
}

// Initialize mocks base method.
func (m *MockFileStore) Initialize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Initialize")
}

// Initialize indicates an expected call of Initialize.
func (mr *MockFileStoreMockRecorder) Initialize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockFileStore)(nil).Initialize))
}

// UpdateFile mocks base method.
func (m *MockFileStore) UpdateFile(path utils.SyncedFile) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateFile", path)
}

// UpdateFile indicates an expected call of UpdateFile.
func (mr *MockFileStoreMockRecorder) UpdateFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockFileStore)(nil).UpdateFile), path)
}
